### PR TITLE
fix appdata fial

### PR DESCRIPTION
**Pull request by FireController1847**
yes i kept the name like it is

### CODE REVIEW

**Comment by FireController1847** [comment]
#burritofounditandthenitookhischancetomakeapullrequestbutialsorecognizeditbuthethinksijustreadhismessage

**Comment by burritosoftware** [comment]
**NO PLEASE FIAR**

**Comment by burritosoftware** [comment]
**NO PLEASE FIAR**

**Comment by 1Revenger1** [comment]
Lol, hold on, let me check with some people who have P3D.

**Comment by 1Revenger1** [comment]
Alright. If you make the same edit for the FSX directory as well, I'll accept this @FireController1847

**Pull request merged**
